name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        distribution: 'adopt'
        java-version: '8'

    - name: Build with Maven
      working-directory: src/main/java/my-java-project
      run: mvn clean package

    - name: Install AWS CLI
      run: |
        curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
        unzip awscliv2.zip
        sudo ./aws/install
        aws --version  # Verify AWS CLI installation

    - name: Upload to S3
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: 'us-east-1'
        S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }}
      run: |
        ls -l src/main/java/my-java-project/target/  # Debugging step
        aws s3 cp src/main/java/my-java-project/target/my-java-project-1.0-SNAPSHOT.jar s3://$S3_BUCKET_NAME/
